<?php
/**
 * Lightweight schema upgrades for role, pricing, and stock-audit features.
 * Safe to include multiple times; PostgreSQL/Supabase ignores existing columns.
 */
if (!function_exists('ensureBossPricingSchema')) {
    function ensureBossPricingSchema(PDO $conn): void
    {
        $conn->exec("ALTER TABLE admin ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'admin'");
        $conn->exec("ALTER TABLE admin ADD COLUMN IF NOT EXISTS display_name TEXT");
        $conn->exec("UPDATE admin SET role = 'admin' WHERE role IS NULL OR role = ''");

        $conn->exec("ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2) DEFAULT 0");
        $conn->exec("ALTER TABLE products ADD COLUMN IF NOT EXISTS online_sell_price NUMERIC(10,2) DEFAULT 0");
        $conn->exec("UPDATE products SET cost_price = 0 WHERE cost_price IS NULL");
        $conn->exec("UPDATE products SET online_sell_price = 0 WHERE online_sell_price IS NULL");
    }
}

if (!function_exists('ensureStockHistoryAuditSchema')) {
    function ensureStockHistoryAuditSchema(PDO $conn): void
    {
        $conn->exec("ALTER TABLE stock_history ADD COLUMN IF NOT EXISTS edited_by_admin_id BIGINT");
        $conn->exec("ALTER TABLE stock_history ADD COLUMN IF NOT EXISTS edited_by_admin_name TEXT");
    }
}



if (!function_exists('ensureInventoryMovementSchema')) {
    function ensureInventoryMovementSchema(PDO $conn): void
    {
        ensureStockHistoryAuditSchema($conn);
        $conn->exec("ALTER TABLE stock_history ADD COLUMN IF NOT EXISTS quantity_before INTEGER DEFAULT 0");
        $conn->exec("ALTER TABLE stock_history ADD COLUMN IF NOT EXISTS quantity_after INTEGER DEFAULT 0");
        $conn->exec("ALTER TABLE stock_history ADD COLUMN IF NOT EXISTS note TEXT");
        $conn->exec("CREATE TABLE IF NOT EXISTS product_colors (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
            color_name TEXT NOT NULL DEFAULT '',
            color_code TEXT NOT NULL DEFAULT '#000000',
            is_default BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
        )");
        $conn->exec("ALTER TABLE product_sizes ADD COLUMN IF NOT EXISTS color_id BIGINT");
        $conn->exec("ALTER TABLE stock_history ADD COLUMN IF NOT EXISTS color_id BIGINT");

        // Create a default colour for legacy products that have stock rows but no colours.
        // This helps older stock data move into the new product + colour + size workflow safely.
        try {
            $conn->exec("INSERT INTO product_colors (product_id, color_name, color_code, is_default)
                SELECT p.id, 'Default', '#000000', TRUE
                FROM products p
                WHERE EXISTS (SELECT 1 FROM product_sizes ps WHERE ps.product_id = p.id AND ps.color_id IS NULL)
                  AND NOT EXISTS (SELECT 1 FROM product_colors pc WHERE pc.product_id = p.id)");

            // If a product has exactly one colour, assign old NULL-colour stock/history to that colour.
            // Products with multiple colours are left as legacy rows so admin can review them manually.
            $conn->exec("WITH single_colour AS (
                    SELECT product_id, MIN(id) AS color_id
                    FROM product_colors
                    GROUP BY product_id
                    HAVING COUNT(*) = 1
                )
                UPDATE product_sizes ps
                SET color_id = sc.color_id
                FROM single_colour sc
                WHERE ps.product_id = sc.product_id
                  AND ps.color_id IS NULL");

            $conn->exec("WITH single_colour AS (
                    SELECT product_id, MIN(id) AS color_id
                    FROM product_colors
                    GROUP BY product_id
                    HAVING COUNT(*) = 1
                )
                UPDATE stock_history sh
                SET color_id = sc.color_id
                FROM single_colour sc
                WHERE sh.product_id = sc.product_id
                  AND sh.color_id IS NULL");
        } catch (Throwable $e) {
            // Keep page loading; run database/latest_database_schema.sql manually if needed.
        }

        // Inventory is now tracked by product + colour + size. Remove old product + size rule.
        try {
            $conn->exec("ALTER TABLE product_sizes DROP CONSTRAINT IF EXISTS product_sizes_product_id_size_key");
        } catch (Throwable $e) {
            // Keep page loading; the SQL upgrade file can be run manually if needed.
        }

        try {
            $conn->exec("DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'product_sizes_product_color_size_key'
                ) THEN
                    ALTER TABLE product_sizes
                    ADD CONSTRAINT product_sizes_product_color_size_key
                    UNIQUE (product_id, color_id, size);
                END IF;
            END $$;");
        } catch (Throwable $e) {
            // If existing duplicate rows block the constraint, run the SQL cleanup file manually.
        }

        $conn->exec("UPDATE stock_history SET quantity_before = 0 WHERE quantity_before IS NULL");
        $conn->exec("UPDATE stock_history SET quantity_after = quantity WHERE quantity_after IS NULL");
    }
}


if (!function_exists('adminCsrfInput')) {
    function adminCsrfInput(): string
    {
        $token = $_SESSION['csrf_token'] ?? '';
        return '<input type="hidden" name="csrf_token" value="' . htmlspecialchars((string)$token, ENT_QUOTES, 'UTF-8') . '">';
    }
}

if (!function_exists('isValidAdminCsrfToken')) {
    function isValidAdminCsrfToken(): bool
    {
        $postedToken = (string)($_POST['csrf_token'] ?? '');
        $sessionToken = (string)($_SESSION['csrf_token'] ?? '');
        return $postedToken !== '' && $sessionToken !== '' && hash_equals($sessionToken, $postedToken);
    }
}

if (!function_exists('currentAdminDisplayName')) {
    function currentAdminDisplayName(): string
    {
        $name = $_SESSION['admin_name'] ?? $_SESSION['admin_email'] ?? 'Admin';
        $name = trim((string)$name);
        return $name !== '' ? $name : 'Admin';
    }
}
