-- ==========================================================
-- My Dream Bike Store Management System
-- Latest Supabase/PostgreSQL database schema backup file
-- Version: v54 project cleanup
-- Purpose: Keep a clean backup of the latest table structure used by the PHP project.
--
-- IMPORTANT:
-- 1. This file backs up/creates the latest schema structure only.
-- 2. It does not contain your live product/customer/admin data.
-- 3. For a full data backup, use Supabase Dashboard export or pg_dump.
-- 4. This file is safe to keep in the project because it does not include secrets.
-- ==========================================================

BEGIN;

-- Optional helper to auto-update updated_at columns.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==========================================================
-- Core admin table
-- ==========================================================
CREATE TABLE IF NOT EXISTS admin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  display_name TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE admin
ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'admin',
ADD COLUMN IF NOT EXISTS display_name TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

-- ==========================================================
-- Customer table
-- ==========================================================
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  password TEXT NOT NULL,
  google_id TEXT UNIQUE,
  auth_provider TEXT DEFAULT 'email',
  profile_picture TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE customers
ADD COLUMN IF NOT EXISTS google_id TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS auth_provider TEXT DEFAULT 'email',
ADD COLUMN IF NOT EXISTS profile_picture TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

-- ==========================================================
-- Products
-- ==========================================================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  category TEXT NOT NULL,
  sub_category TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  cost_price NUMERIC(10,2) DEFAULT 0,
  online_sell_price NUMERIC(10,2) DEFAULT 0,
  description TEXT,
  image TEXT DEFAULT '',
  arrival_date DATE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE products
ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS online_sell_price NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS image TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS arrival_date DATE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

-- ==========================================================
-- Product colours and images
-- ==========================================================
CREATE TABLE IF NOT EXISTS product_colors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  color_name TEXT NOT NULL DEFAULT '',
  color_code TEXT NOT NULL DEFAULT '#000000',
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  color_id BIGINT REFERENCES product_colors(id) ON DELETE SET NULL,
  image_path TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_main BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- ==========================================================
-- Product colour + size stock table
-- ==========================================================
CREATE TABLE IF NOT EXISTS product_sizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  color_id BIGINT REFERENCES product_colors(id) ON DELETE CASCADE,
  size TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE product_sizes
ADD COLUMN IF NOT EXISTS color_id BIGINT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

-- Assign old NULL colour stock rows to a default colour before the new unique rule.
INSERT INTO product_colors (product_id, color_name, color_code, is_default)
SELECT p.id, 'Default', '#000000', TRUE
FROM products p
WHERE EXISTS (
    SELECT 1 FROM product_sizes ps
    WHERE ps.product_id = p.id AND ps.color_id IS NULL
)
AND NOT EXISTS (
    SELECT 1 FROM product_colors pc
    WHERE pc.product_id = p.id AND LOWER(pc.color_name) = 'default'
);

UPDATE product_sizes ps
SET color_id = pc.id
FROM product_colors pc
WHERE ps.product_id = pc.product_id
  AND ps.color_id IS NULL
  AND LOWER(pc.color_name) = 'default';

-- Merge duplicate stock rows for same product + colour + size before adding unique rule.
WITH duplicate_groups AS (
    SELECT
        product_id,
        color_id,
        size,
        MIN(id) AS keep_id,
        SUM(COALESCE(quantity, 0)) AS total_quantity
    FROM product_sizes
    GROUP BY product_id, color_id, size
    HAVING COUNT(*) > 1
), update_kept AS (
    UPDATE product_sizes ps
    SET quantity = dg.total_quantity
    FROM duplicate_groups dg
    WHERE ps.id = dg.keep_id
    RETURNING ps.id
)
DELETE FROM product_sizes ps
USING duplicate_groups dg
WHERE ps.product_id = dg.product_id
  AND ps.color_id IS NOT DISTINCT FROM dg.color_id
  AND ps.size = dg.size
  AND ps.id <> dg.keep_id;

-- Remove old unique rule and apply latest colour + size unique rule.
ALTER TABLE product_sizes
DROP CONSTRAINT IF EXISTS product_sizes_product_id_size_key;

ALTER TABLE product_sizes
DROP CONSTRAINT IF EXISTS product_sizes_product_color_size_key;

ALTER TABLE product_sizes
ADD CONSTRAINT product_sizes_product_color_size_key
UNIQUE (product_id, color_id, size);

-- ==========================================================
-- Stock movement history / audit table
-- ==========================================================
CREATE TABLE IF NOT EXISTS stock_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  color_id BIGINT REFERENCES product_colors(id) ON DELETE SET NULL,
  size TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('IN', 'OUT')),
  quantity INTEGER NOT NULL,
  reason TEXT DEFAULT '',
  quantity_before INTEGER DEFAULT 0,
  quantity_after INTEGER DEFAULT 0,
  note TEXT,
  edited_by_admin_id BIGINT,
  edited_by_admin_name TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE stock_history
ADD COLUMN IF NOT EXISTS color_id BIGINT,
ADD COLUMN IF NOT EXISTS quantity_before INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS quantity_after INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS note TEXT,
ADD COLUMN IF NOT EXISTS edited_by_admin_id BIGINT,
ADD COLUMN IF NOT EXISTS edited_by_admin_name TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

UPDATE stock_history
SET quantity_before = 0
WHERE quantity_before IS NULL;

UPDATE stock_history
SET quantity_after = quantity
WHERE quantity_after IS NULL;

UPDATE stock_history
SET edited_by_admin_name = 'Not recorded'
WHERE edited_by_admin_name IS NULL OR edited_by_admin_name = '';

-- ==========================================================
-- Triggers
-- ==========================================================
DROP TRIGGER IF EXISTS trg_admin_updated_at ON admin;
CREATE TRIGGER trg_admin_updated_at
BEFORE UPDATE ON admin
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_product_sizes_updated_at ON product_sizes;
CREATE TRIGGER trg_product_sizes_updated_at
BEFORE UPDATE ON product_sizes
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_stock_history_updated_at ON stock_history;
CREATE TRIGGER trg_stock_history_updated_at
BEFORE UPDATE ON stock_history
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ==========================================================
-- Indexes
-- ==========================================================
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_sub_category ON products(sub_category);
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);
CREATE INDEX IF NOT EXISTS idx_product_colors_product_id ON product_colors(product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_color_id ON product_images(color_id);
CREATE INDEX IF NOT EXISTS idx_product_sizes_product_id ON product_sizes(product_id);
CREATE INDEX IF NOT EXISTS idx_product_sizes_product_color_size ON product_sizes(product_id, color_id, size);
CREATE INDEX IF NOT EXISTS idx_stock_history_product_id ON stock_history(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_history_product_color_size ON stock_history(product_id, color_id, size);
CREATE INDEX IF NOT EXISTS idx_stock_history_created_at ON stock_history(created_at);

COMMIT;
