-- Colour + size inventory support for My Dream Bike
-- Run this in Supabase SQL Editor before using colour-specific Stock In / Stock Out.
-- This version fixes the old product_id + size unique rule and helps migrate old NULL colour stock rows safely.

BEGIN;

-- 1. Make sure required columns/tables exist.
CREATE TABLE IF NOT EXISTS product_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color_name TEXT NOT NULL DEFAULT '',
    color_code TEXT NOT NULL DEFAULT '#000000',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

ALTER TABLE product_sizes
ADD COLUMN IF NOT EXISTS color_id BIGINT;

ALTER TABLE stock_history
ADD COLUMN IF NOT EXISTS color_id BIGINT,
ADD COLUMN IF NOT EXISTS quantity_before INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS quantity_after INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS note TEXT,
ADD COLUMN IF NOT EXISTS edited_by_admin_id BIGINT,
ADD COLUMN IF NOT EXISTS edited_by_admin_name TEXT;

-- 2. Create a Default colour for old products that have stock rows but no colour records.
INSERT INTO product_colors (product_id, color_name, color_code, is_default)
SELECT p.id, 'Default', '#000000', TRUE
FROM products p
WHERE EXISTS (
    SELECT 1
    FROM product_sizes ps
    WHERE ps.product_id = p.id
      AND ps.color_id IS NULL
)
AND NOT EXISTS (
    SELECT 1
    FROM product_colors pc
    WHERE pc.product_id = p.id
);

-- 3. If a product has exactly one colour, old NULL-colour stock rows can safely be assigned to that colour.
-- Products with multiple colours are left as NULL so admin can review and re-add stock correctly by colour.
WITH single_colour AS (
    SELECT product_id, MIN(id) AS color_id
    FROM product_colors
    GROUP BY product_id
    HAVING COUNT(*) = 1
)
UPDATE product_sizes ps
SET color_id = sc.color_id
FROM single_colour sc
WHERE ps.product_id = sc.product_id
  AND ps.color_id IS NULL;

WITH single_colour AS (
    SELECT product_id, MIN(id) AS color_id
    FROM product_colors
    GROUP BY product_id
    HAVING COUNT(*) = 1
)
UPDATE stock_history sh
SET color_id = sc.color_id
FROM single_colour sc
WHERE sh.product_id = sc.product_id
  AND sh.color_id IS NULL;

-- 4. Merge exact duplicate product + colour + size rows before adding the new unique rule.
-- This prevents duplicate-key errors if old data already contains repeated rows.
WITH grouped AS (
    SELECT product_id, color_id, TRIM(size) AS clean_size, MIN(id) AS keep_id, SUM(COALESCE(quantity, 0)) AS total_quantity
    FROM product_sizes
    WHERE color_id IS NOT NULL
      AND NULLIF(TRIM(size), '') IS NOT NULL
    GROUP BY product_id, color_id, TRIM(size)
), updated AS (
    UPDATE product_sizes ps
    SET quantity = g.total_quantity,
        size = g.clean_size
    FROM grouped g
    WHERE ps.id = g.keep_id
    RETURNING ps.id
)
DELETE FROM product_sizes ps
USING grouped g
WHERE ps.product_id = g.product_id
  AND ps.color_id = g.color_id
  AND TRIM(ps.size) = g.clean_size
  AND ps.id <> g.keep_id;

-- 5. Remove the old database rule that only allowed one size per product.
ALTER TABLE product_sizes
DROP CONSTRAINT IF EXISTS product_sizes_product_id_size_key;

-- 6. Add the new database rule: same size can exist for different colours, but not duplicated within the same colour.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'product_sizes_product_color_size_key'
    ) THEN
        ALTER TABLE product_sizes
        ADD CONSTRAINT product_sizes_product_color_size_key
        UNIQUE (product_id, color_id, size);
    END IF;
END $$;

-- 7. Helpful indexes for stock pages and filters.
CREATE INDEX IF NOT EXISTS idx_product_sizes_product_color_size
ON product_sizes (product_id, color_id, size);

CREATE INDEX IF NOT EXISTS idx_stock_history_product_color_size
ON stock_history (product_id, color_id, size);

UPDATE stock_history SET quantity_before = 0 WHERE quantity_before IS NULL;
UPDATE stock_history SET quantity_after = quantity WHERE quantity_after IS NULL;
UPDATE stock_history SET edited_by_admin_name = 'Not recorded' WHERE edited_by_admin_name IS NULL OR edited_by_admin_name = '';

COMMIT;

-- 8. Manual review list.
-- If this returns rows, those products had old stock but multiple colours, so the system cannot know which colour the stock belongs to.
-- Re-add the correct quantities through Stock In, then remove/correct the legacy rows manually if needed.
SELECT p.id AS product_id,
       p.item_code,
       p.name,
       ps.id AS product_size_id,
       ps.size,
       ps.quantity,
       'Needs manual colour assignment' AS action_needed
FROM product_sizes ps
JOIN products p ON p.id = ps.product_id
WHERE ps.color_id IS NULL
ORDER BY p.name, ps.size;
