<?php
require_once 'includes/auth_check.php';
require_once '../config/database.php';
require_once 'includes/schema_helpers.php';
ensureBossPricingSchema($conn);
ensureInventoryMovementSchema($conn);
$isBoss = isBossAdmin();

$page_title = 'Add Product';
$error      = '';

// Ensure color/image tables exist in PostgreSQL/Supabase
$conn->exec("CREATE TABLE IF NOT EXISTS product_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color_name TEXT NOT NULL DEFAULT '',
    color_code TEXT NOT NULL DEFAULT '#000000',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
)");
$conn->exec("CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color_id BIGINT REFERENCES product_colors(id) ON DELETE SET NULL,
    image_path TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_main BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
)");

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!isValidAdminCsrfToken()) {
        $error = 'Invalid security token. Please refresh the page and try again.';
    } else {
    $item_code    = trim($_POST['item_code']    ?? '');
    $name         = trim($_POST['name']         ?? '');
    $category     = trim($_POST['category']     ?? '');
    $sub_category = trim($_POST['sub_category'] ?? '');
    $brand        = trim($_POST['brand']        ?? '');
    $status       = trim($_POST['status']       ?? 'ACTIVE');
    $price        = floatval($_POST['price']    ?? 0);
    $cost_price   = $isBoss ? floatval($_POST['cost_price'] ?? 0) : 0;
    $online_sell_price = $isBoss ? floatval($_POST['online_sell_price'] ?? 0) : 0;
    $description  = trim($_POST['description']  ?? '');
    $arrival_date = $_POST['arrival_date']      ?? date('Y-m-d');

    // Validation
    if (empty($item_code) || empty($name) || empty($category) || empty($sub_category) || empty($brand)) {
        $error = 'Please fill in all required fields.';
    } else {
        $check = $conn->prepare("SELECT id FROM products WHERE item_code = ?");
        $check->execute([$item_code]);
        if ($check->fetch()) {
            $error = 'Item code "' . htmlspecialchars($item_code) . '" already exists.';
        }
    }

    if (!$error) {
        $stmt = $conn->prepare("INSERT INTO products (item_code, name, brand, category, sub_category, status, price, cost_price, online_sell_price, description, arrival_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id");
        if ($stmt->execute([$item_code, $name, $brand, $category, $sub_category, $status, $price, $cost_price, $online_sell_price, $description, $arrival_date])) {
            $product_id = (int) $stmt->fetchColumn();

            $_SESSION['success'] = 'Product "' . htmlspecialchars($name) . '" added! Now set up its colors and images.';
            header("Location: manage_product_colors.php?product_id=$product_id&new=1");
            exit();
        } else {
            $error = 'Failed to save product. Please try again.';
        }
    }
    }
}

require_once 'includes/header.php';
?>

<?php if ($error): ?>
<div class="alert alert-danger"><?php echo htmlspecialchars($error); ?></div>
<?php endif; ?>

<div class="form-container">
    <form method="POST" action="add_product.php">
        <?php echo adminCsrfInput(); ?>

        <div class="form-section-title">Basic Information</div>

        <div class="form-row">
            <div class="form-group">
                <label for="item_code">Item Code <span class="required">*</span></label>
                <input type="text" id="item_code" name="item_code"
                       placeholder="e.g. HEL-001"
                       value="<?php echo htmlspecialchars($_POST['item_code'] ?? ''); ?>" required>
            </div>
            <div class="form-group">
                <label for="name">Product Name <span class="required">*</span></label>
                <input type="text" id="name" name="name"
                       placeholder="e.g. AGV K1 Full Face Helmet"
                       value="<?php echo htmlspecialchars($_POST['name'] ?? ''); ?>" required>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="brand">Brand <span class="required">*</span></label>
                <input type="text" id="brand" name="brand"
                       placeholder="e.g. AGV, Shoei, HJC"
                       value="<?php echo htmlspecialchars($_POST['brand'] ?? ''); ?>" required>
            </div>
            <div class="form-group">
                <label for="price">Price (RM) <span class="required">*</span></label>
                <input type="number" id="price" name="price" step="0.01" min="0"
                       value="<?php echo htmlspecialchars($_POST['price'] ?? ''); ?>" required>
            </div>
        </div>

        <?php if ($isBoss): ?>
        <div class="boss-only-box">
            <div class="form-section-title">Boss-Only Pricing</div>
            <p class="boss-note">Only boss admins can view and edit cost price and online sell price.</p>
            <div class="form-row">
                <div class="form-group">
                    <label for="cost_price">Cost Price (RM)</label>
                    <input type="number" id="cost_price" name="cost_price" step="0.01" min="0"
                           value="<?php echo htmlspecialchars($_POST['cost_price'] ?? '0.00'); ?>">
                </div>
                <div class="form-group">
                    <label for="online_sell_price">Online Sell Price (RM)</label>
                    <input type="number" id="online_sell_price" name="online_sell_price" step="0.01" min="0"
                           value="<?php echo htmlspecialchars($_POST['online_sell_price'] ?? '0.00'); ?>">
                </div>
            </div>
        </div>
        <?php endif; ?>

        <div class="form-row">
            <div class="form-group">
                <label for="category">Main Category <span class="required">*</span></label>
                <select id="category" name="category" required onchange="updateSubCategories(this.value, '')">
                    <option value="">-- Select Category --</option>
                    <option value="Helmet"      <?php echo (($_POST['category'] ?? '') === 'Helmet')      ? 'selected' : ''; ?>>Helmet</option>
                    <option value="Apparel"     <?php echo (($_POST['category'] ?? '') === 'Apparel')     ? 'selected' : ''; ?>>Apparel</option>
                    <option value="Accessories" <?php echo (($_POST['category'] ?? '') === 'Accessories') ? 'selected' : ''; ?>>Accessories</option>
                </select>
            </div>
            <div class="form-group">
                <label for="sub_category">Sub Category <span class="required">*</span></label>
                <select id="sub_category" name="sub_category" required>
                    <option value="">-- Select Sub Category --</option>
                    <?php
                    $subs = [
                        'Helmet'      => ['Full Face Helmet','Open Face Helmet','Flip Up Helmet','Off Road Helmet','Kid Helmet'],
                        'Apparel'     => ['Jackets','Pants','Gloves','Rain Gear'],
                        'Accessories' => ['Bags','Disc Lock','Helmet Accessories','Other Accessories'],
                    ];
                    $cat = $_POST['category'] ?? '';
                    $sub = $_POST['sub_category'] ?? '';
                    if (isset($subs[$cat])) {
                        foreach ($subs[$cat] as $s)
                            echo "<option value=\"$s\"" . ($s === $sub ? ' selected' : '') . ">$s</option>";
                    }
                    ?>
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="status">Status</label>
                <select id="status" name="status">
                    <option value="ACTIVE">Active</option>
                    <option value="HIDDEN">Hidden</option>
                    <option value="OUT_OF_STOCK">Out of Stock</option>
                </select>
            </div>
            <div class="form-group">
                <label for="arrival_date">Arrival Date</label>
                <input type="date" id="arrival_date" name="arrival_date"
                       value="<?php echo htmlspecialchars($_POST['arrival_date'] ?? date('Y-m-d')); ?>">
            </div>
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea id="description" name="description" rows="4"
                      placeholder="Describe the product..."><?php echo htmlspecialchars($_POST['description'] ?? ''); ?></textarea>
        </div>



        <div class="form-actions">
            <button type="submit" class="btn btn-primary btn-lg">Save &amp; Set Up Colors →</button>
            <a href="products.php" class="btn btn-secondary btn-lg">Cancel</a>
        </div>

    </form>
</div>

<style>
.form-section-title {
    font-size: 13px; font-weight: 700; color: #ff7a00;
    text-transform: uppercase; letter-spacing: 1px;
    margin-bottom: 16px; padding-bottom: 8px;
    border-bottom: 1px solid #e0e0e0;
}
</style>

<script>
const subCategories = {
    Helmet:      ['Full Face Helmet','Open Face Helmet','Flip Up Helmet','Off Road Helmet','Kid Helmet'],
    Apparel:     ['Jackets','Pants','Gloves','Rain Gear'],
    Accessories: ['Bags','Disc Lock','Helmet Accessories','Other Accessories'],
};

function updateSubCategories(cat, selected) {
    const sel = document.getElementById('sub_category');
    sel.innerHTML = '<option value="">-- Select Sub Category --</option>';
    (subCategories[cat] || []).forEach(s => {
        const o = document.createElement('option');
        o.value = o.textContent = s;
        if (s === selected) o.selected = true;
        sel.appendChild(o);
    });
}

// Restore sub-category on page reload (validation error)
(function() {
    const cat = document.getElementById('category').value;
    const sub = '<?php echo addslashes($_POST['sub_category'] ?? ''); ?>';
    if (cat) updateSubCategories(cat, sub);
})();

</script>

<?php require_once 'includes/footer.php'; $conn = null; ?>
