<?php
require_once 'includes/auth_check.php';
require_once '../config/database.php';
require_once 'includes/schema_helpers.php';
ensureInventoryMovementSchema($conn);

$page_title = 'Colors & Images';
$product_id = isset($_GET['product_id']) ? intval($_GET['product_id']) : 0;

$stmt = $conn->prepare("SELECT id, name, item_code, category, sub_category, brand FROM products WHERE id = ?");
$stmt->execute([$product_id]);
$product = $stmt->fetch();
if (!$product) {
    header("Location: products.php");
    exit();
}

$conn->exec("CREATE TABLE IF NOT EXISTS product_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color_name TEXT NOT NULL DEFAULT '',
    color_code TEXT NOT NULL DEFAULT '#000000',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
)");
$conn->exec("CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color_id BIGINT REFERENCES product_colors(id) ON DELETE SET NULL,
    image_path TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_main BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
)");

function color_exists_for_product(PDO $conn, int $colorId, int $productId): bool {
    $stmt = $conn->prepare("SELECT 1 FROM product_colors WHERE id = ? AND product_id = ? LIMIT 1");
    $stmt->execute([$colorId, $productId]);
    return (bool) $stmt->fetchColumn();
}

function pg_bool($value): bool {
    return $value === true || $value === 1 || $value === '1' || $value === 't' || $value === 'true';
}

function pg_bool_value($value): string {
    return $value ? 'true' : 'false';
}

$flash_ok = '';
$flash_err = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!isValidAdminCsrfToken()) {
        $_SESSION['mpc_err'] = 'Invalid security token. Please refresh the page and try again.';
        $_SESSION['mpc_ok'] = '';
        header('Location: manage_product_colors.php?product_id=' . $product_id);
        exit();
    }

    $action = $_POST['action'] ?? '';

    if ($action === 'add_color') {
        $cname = trim($_POST['color_name'] ?? '');
        $ccode = trim($_POST['color_code'] ?? '#000000');
        $is_def = isset($_POST['is_default']);

        if ($cname === '') {
            $flash_err = 'Color name is required.';
        } else {
            $countStmt = $conn->prepare("SELECT COUNT(*) FROM product_colors WHERE product_id = ?");
            $countStmt->execute([$product_id]);
            if ((int) $countStmt->fetchColumn() === 0) {
                $is_def = true;
            }

            if ($is_def) {
                $conn->prepare("UPDATE product_colors SET is_default = FALSE WHERE product_id = ?")->execute([$product_id]);
            }

            $conn->prepare("INSERT INTO product_colors (product_id, color_name, color_code, is_default) VALUES (?, ?, ?, ?)")
                 ->execute([$product_id, $cname, $ccode, pg_bool_value($is_def)]);
            $flash_ok = 'Color added successfully.';
        }
    }

    elseif ($action === 'save_colors') {
        $colorIds    = $_POST['color_ids'] ?? [];
        $colorNames  = $_POST['color_name'] ?? [];
        $colorCodes  = $_POST['color_code'] ?? [];
        $defaultId   = intval($_POST['default_color_id'] ?? 0);

        if (empty($colorIds)) {
            $flash_err = 'There are no colors to update.';
        } else {
            try {
                $conn->beginTransaction();

                $validColorIds = [];
                $updateStmt = $conn->prepare("UPDATE product_colors SET color_name = ?, color_code = ?, is_default = FALSE WHERE id = ? AND product_id = ?");

                foreach ($colorIds as $cid) {
                    $cid = intval($cid);
                    if ($cid <= 0 || !color_exists_for_product($conn, $cid, $product_id)) {
                        continue;
                    }

                    $name = trim($colorNames[$cid] ?? '');
                    $code = trim($colorCodes[$cid] ?? '#000000');
                    if ($name === '') {
                        throw new RuntimeException('Each color must have a name.');
                    }
                    if (!preg_match('/^#[0-9A-Fa-f]{6}$/', $code)) {
                        $code = '#000000';
                    }

                    $updateStmt->execute([$name, $code, $cid, $product_id]);
                    $validColorIds[] = $cid;
                }

                if (empty($validColorIds)) {
                    throw new RuntimeException('No valid colors were found to update.');
                }

                if (!in_array($defaultId, $validColorIds, true)) {
                    $defaultId = $validColorIds[0];
                }

                $conn->prepare("UPDATE product_colors SET is_default = FALSE WHERE product_id = ?")->execute([$product_id]);
                $conn->prepare("UPDATE product_colors SET is_default = TRUE WHERE id = ? AND product_id = ?")->execute([$defaultId, $product_id]);

                $conn->commit();
                $flash_ok = 'Color details saved successfully.';
            } catch (Throwable $e) {
                if ($conn->inTransaction()) {
                    $conn->rollBack();
                }
                $flash_err = $e->getMessage();
            }
        }
    }

    elseif ($action === 'delete_color') {
        $cid = intval($_POST['color_id'] ?? 0);

        if ($cid <= 0 || !color_exists_for_product($conn, $cid, $product_id)) {
            $flash_err = 'Invalid color selected.';
        } else {
            $stockStmt = $conn->prepare("SELECT COALESCE(SUM(quantity), 0) FROM product_sizes WHERE product_id = ? AND color_id = ?");
            $stockStmt->execute([$product_id, $cid]);
            $currentStock = (int) $stockStmt->fetchColumn();

            if ($currentStock > 0) {
                $flash_err = 'Cannot delete this color because it still has ' . $currentStock . ' unit(s) in stock. Please use Stock Out to remove the stock first.';
            } else {
                try {
                    $conn->beginTransaction();

                    $imgs = $conn->prepare("SELECT image_path FROM product_images WHERE color_id = ? AND product_id = ?");
                    $imgs->execute([$cid, $product_id]);
                    $imagePaths = $imgs->fetchAll();

                    $conn->prepare("DELETE FROM product_images WHERE color_id = ? AND product_id = ?")->execute([$cid, $product_id]);
                    $conn->prepare("DELETE FROM product_sizes WHERE product_id = ? AND color_id = ? AND COALESCE(quantity, 0) = 0")->execute([$product_id, $cid]);
                    $conn->prepare("DELETE FROM product_colors WHERE id = ? AND product_id = ?")->execute([$cid, $product_id]);

                    $next = $conn->prepare("SELECT id FROM product_colors WHERE product_id = ? ORDER BY id ASC LIMIT 1");
                    $next->execute([$product_id]);
                    $nextColor = $next->fetch();
                    if ($nextColor) {
                        $conn->prepare("UPDATE product_colors SET is_default = TRUE WHERE id = ?")->execute([$nextColor['id']]);
                    }

                    $conn->commit();

                    foreach ($imagePaths as $img) {
                        $filePath = '../' . $img['image_path'];
                        if (is_file($filePath)) {
                            unlink($filePath);
                        }
                    }

                    $flash_ok = 'Color and its images were deleted.';
                } catch (Throwable $e) {
                    if ($conn->inTransaction()) {
                        $conn->rollBack();
                    }
                    $flash_err = 'Failed to delete color: ' . $e->getMessage();
                }
            }
        }
    }

    elseif ($action === 'upload_images') {
        $cid = intval($_POST['color_id'] ?? 0);

        if (!color_exists_for_product($conn, $cid, $product_id)) {
            $flash_err = 'Invalid color selected.';
        } elseif (!isset($_FILES['images']) || empty($_FILES['images']['name'][0])) {
            $flash_err = 'Please select at least one image.';
        } else {
            $uploadDir = '../uploads/';
            if (!is_dir($uploadDir)) {
                mkdir($uploadDir, 0755, true);
            }

            $allowed = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
            $maxSize = 5 * 1024 * 1024;

            $sortStmt = $conn->prepare("SELECT COALESCE(MAX(sort_order), 0) FROM product_images WHERE color_id = ?");
            $sortStmt->execute([$cid]);
            $sortBase = (int) $sortStmt->fetchColumn() + 1;

            $countStmt = $conn->prepare("SELECT COUNT(*) FROM product_images WHERE color_id = ?");
            $countStmt->execute([$cid]);
            $existingCount = (int) $countStmt->fetchColumn();

            $insertStmt = $conn->prepare("INSERT INTO product_images (product_id, color_id, image_path, sort_order, is_main) VALUES (?, ?, ?, ?, ?)");

            $done = 0;
            $skipped = 0;
            foreach ($_FILES['images']['name'] as $i => $filename) {
                if (($_FILES['images']['error'][$i] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
                    $skipped++;
                    continue;
                }

                $ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
                if (!in_array($ext, $allowed, true)) {
                    $skipped++;
                    continue;
                }

                if (($_FILES['images']['size'][$i] ?? 0) > $maxSize) {
                    $skipped++;
                    continue;
                }

                $newName = 'pimg_' . $product_id . '_' . $cid . '_' . bin2hex(random_bytes(6)) . '.' . $ext;
                if (move_uploaded_file($_FILES['images']['tmp_name'][$i], $uploadDir . $newName)) {
                    $isMain = ($existingCount === 0 && $done === 0);
                    $insertStmt->execute([$product_id, $cid, 'uploads/' . $newName, $sortBase + $done, pg_bool_value($isMain)]);
                    $done++;
                } else {
                    $skipped++;
                }
            }

            $flash_ok = $done . ' image(s) uploaded.' . ($skipped ? ' ' . $skipped . ' skipped.' : '');
        }
    }

    elseif ($action === 'set_main') {
        $imgId = intval($_POST['image_id'] ?? 0);
        $cid = intval($_POST['color_id'] ?? 0);
        $conn->prepare("UPDATE product_images SET is_main = FALSE WHERE color_id = ?")->execute([$cid]);
        $conn->prepare("UPDATE product_images SET is_main = TRUE WHERE id = ? AND product_id = ?")->execute([$imgId, $product_id]);
        $flash_ok = 'Main image updated.';
    }

    elseif ($action === 'delete_image') {
        $imgId = intval($_POST['image_id'] ?? 0);
        $cid   = intval($_POST['color_id'] ?? 0);

        $stmt = $conn->prepare("SELECT image_path, is_main FROM product_images WHERE id = ? AND product_id = ?");
        $stmt->execute([$imgId, $product_id]);
        $img = $stmt->fetch();

        if ($img) {
            $filePath = '../' . $img['image_path'];
            if (is_file($filePath)) {
                unlink($filePath);
            }

            $conn->prepare("DELETE FROM product_images WHERE id = ?")->execute([$imgId]);

            if (pg_bool($img['is_main'])) {
                $next = $conn->prepare("SELECT id FROM product_images WHERE color_id = ? ORDER BY sort_order ASC, id ASC LIMIT 1");
                $next->execute([$cid]);
                $nextImage = $next->fetch();
                if ($nextImage) {
                    $conn->prepare("UPDATE product_images SET is_main = TRUE WHERE id = ?")->execute([$nextImage['id']]);
                }
            }

            $flash_ok = 'Image deleted.';
        }
    }

    $_SESSION['mpc_ok'] = $flash_ok;
    $_SESSION['mpc_err'] = $flash_err;
    header('Location: manage_product_colors.php?product_id=' . $product_id);
    exit();
}

$flash_ok = $_SESSION['mpc_ok'] ?? '';
$flash_err = $_SESSION['mpc_err'] ?? '';
unset($_SESSION['mpc_ok'], $_SESSION['mpc_err']);

$colorsStmt = $conn->prepare("SELECT * FROM product_colors WHERE product_id = ? ORDER BY is_default DESC, id ASC");
$colorsStmt->execute([$product_id]);
$colors = $colorsStmt->fetchAll();

$stockByColor = [];
if (!empty($colors)) {
    $stockStmt = $conn->prepare("SELECT color_id, COALESCE(SUM(quantity), 0) AS total_stock FROM product_sizes WHERE product_id = ? AND color_id IS NOT NULL GROUP BY color_id");
    $stockStmt->execute([$product_id]);
    while ($stockRow = $stockStmt->fetch()) {
        $stockByColor[(int)$stockRow['color_id']] = (int)$stockRow['total_stock'];
    }
}

$imagesByColor = [];
if (!empty($colors)) {
    $placeholders = implode(',', array_fill(0, count($colors), '?'));
    $colorIds = array_column($colors, 'id');
    $imgStmt = $conn->prepare("SELECT * FROM product_images WHERE color_id IN ($placeholders) ORDER BY is_main DESC, sort_order ASC, id ASC");
    $imgStmt->execute($colorIds);
    while ($img = $imgStmt->fetch()) {
        $imagesByColor[$img['color_id']][] = $img;
    }
}

require_once 'includes/header.php';
?>

<style>
:root {
    --mpc-bg: #f7f7f9;
    --mpc-bg-soft: #ffffff;
    --mpc-panel: #ffffff;
    --mpc-border: #e5e7eb;
    --mpc-text: #222;
    --mpc-muted: #666;
    --mpc-orange: #ff7a00;
    --mpc-orange-soft: rgba(255, 122, 0, 0.10);
    --mpc-danger: #dc2626;
    --mpc-success: #16a34a;
}

body {
    background: #ffffff;
}

.mpc-page {
    max-width: 1240px;
    margin: 0 auto;
    padding: 10px 10px 30px;
    color: var(--mpc-text);
}
.mpc-flash {
    margin: 0 0 16px;
    padding: 14px 16px;
    border-radius: 14px;
    border: 1px solid transparent;
    font-weight: 600;
}
.mpc-flash.ok { background: #ecfdf3; border-color: #86efac; color: #166534; }
.mpc-flash.err { background: #fef2f2; border-color: #fca5a5; color: #991b1b; }

.mpc-topbar {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 18px;
    padding: 22px;
    border-radius: 18px;
    background: #ffffff;
    border: 1px solid var(--mpc-border);
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.06);
    margin-bottom: 18px;
}
.mpc-kicker {
    display: inline-block;
    margin-bottom: 8px;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.12em;
    color: var(--mpc-orange);
    font-weight: 800;
}
.mpc-title { margin: 0; font-size: 28px; font-weight: 800; color: #222; }
.mpc-sub { margin: 8px 0 0; color: var(--mpc-muted); }
.mpc-meta { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 14px; }
.mpc-pill {
    border: 1px solid var(--mpc-border);
    background: #fff;
    color: #444;
    border-radius: 999px;
    padding: 8px 12px;
    font-size: 13px;
}
.mpc-toolbar {
    display: flex;
    flex-direction: column;
    gap: 10px;
    min-width: 220px;
}
.mpc-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    padding: 11px 16px;
    border-radius: 12px;
    border: 1px solid var(--mpc-border);
    font-weight: 700;
    text-decoration: none;
    cursor: pointer;
    transition: 0.2s ease;
}
.mpc-btn:hover { transform: translateY(-1px); }
.mpc-btn-primary {
    background: var(--mpc-orange);
    color: #111;
    border-color: #ff993f;
}
.mpc-btn-ghost {
    background: #fff;
    color: #333;
}
.mpc-btn-danger {
    background: #fff5f5;
    color: #b91c1c;
    border-color: #fecaca;
}
.mpc-layout {
    display: grid;
    grid-template-columns: 320px minmax(0, 1fr);
    gap: 18px;
}
.mpc-panel {
    background: var(--mpc-panel);
    border: 1px solid var(--mpc-border);
    border-radius: 18px;
    padding: 18px;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.05);
}
.mpc-panel h3 {
    margin: 0 0 14px;
    font-size: 17px;
    color: #222;
}
.mpc-field { margin-bottom: 14px; }
.mpc-label {
    display: block;
    margin-bottom: 8px;
    font-weight: 700;
    color: #333;
}
.mpc-input, .mpc-color-input {
    width: 100%;
    box-sizing: border-box;
    border-radius: 12px;
    border: 1px solid var(--mpc-border);
    background: #fff;
    color: #222;
    padding: 11px 12px;
}
.mpc-color-picker-wrap { display: flex; gap: 10px; align-items: center; }
.mpc-color-input { padding: 4px; width: 62px; height: 44px; }
.mpc-check { display: flex; align-items: center; gap: 10px; color: #444; }
.mpc-tip-list { margin: 0; padding-left: 18px; color: var(--mpc-muted); }
.mpc-tip-list li { margin-bottom: 8px; }
.mpc-main {
    display: flex;
    flex-direction: column;
    gap: 18px;
}
.mpc-empty {
    text-align: center;
    padding: 40px 20px;
    border-radius: 18px;
    border: 1px dashed var(--mpc-border);
    background: #fff;
}
.mpc-cards { display: grid; gap: 18px; }
.mpc-card {
    background: #ffffff;
    border: 1px solid var(--mpc-border);
    border-radius: 20px;
    overflow: hidden;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.05);
}
.mpc-card-head {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 16px;
    padding: 20px;
    border-bottom: 1px solid #f0f0f0;
}
.mpc-card-title-wrap { display: flex; gap: 14px; align-items: center; }
.mpc-swatch {
    width: 52px;
    height: 52px;
    border-radius: 16px;
    border: 1px solid #ddd;
    box-shadow: inset 0 0 0 1px rgba(0,0,0,0.04);
}
.mpc-card-title { margin: 0; font-size: 22px; font-weight: 800; color: #222; }
.mpc-card-sub { margin-top: 6px; color: var(--mpc-muted); }
.mpc-default-badge {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 6px 10px;
    border-radius: 999px;
    background: var(--mpc-orange-soft);
    color: #b45309;
    font-size: 12px;
    font-weight: 800;
    margin-top: 8px;
}
.mpc-card-actions { display: flex; flex-wrap: wrap; gap: 10px; }
.mpc-card-body {
    padding: 20px;
    display: grid;
    grid-template-columns: 340px minmax(0, 1fr);
    gap: 18px;
}
.mpc-edit-grid {
    display: grid;
    gap: 14px;
    align-content: start;
}
.mpc-default-row {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 12px 14px;
    border-radius: 14px;
    background: #fafafa;
    border: 1px solid var(--mpc-border);
}
.mpc-default-row label { font-weight: 700; color: #333; }
.mpc-images { display: grid; gap: 14px; }
.mpc-image-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 14px;
}
.mpc-image-tile,
.mpc-upload-tile {
    background: #ffffff;
    border: 1px solid var(--mpc-border);
    border-radius: 18px;
    overflow: hidden;
}
.mpc-image-preview {
    position: relative;
    aspect-ratio: 1 / 1;
    background: #f5f5f5;
}
.mpc-image-preview img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
}
.mpc-main-image-badge {
    position: absolute;
    top: 10px;
    left: 10px;
    padding: 6px 10px;
    border-radius: 999px;
    background: rgba(255, 122, 0, 0.95);
    color: #141414;
    font-size: 12px;
    font-weight: 800;
}
.mpc-image-actions {
    padding: 12px;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10px;
}
.mpc-image-actions form { margin: 0; }
.mpc-mini-btn {
    width: 100%;
    padding: 9px 10px;
    border-radius: 10px;
    border: 1px solid var(--mpc-border);
    background: #fff;
    color: #333;
    font-weight: 700;
    cursor: pointer;
}
.mpc-mini-btn-danger {
    background: #fff5f5;
    color: #b91c1c;
    border-color: #fecaca;
}
.mpc-upload-tile {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    min-height: 214px;
    padding: 16px;
    border-style: dashed;
    text-align: center;
}
.mpc-upload-tile strong { font-size: 18px; color: #222; }
.mpc-upload-tile p { color: var(--mpc-muted); margin: 8px 0 14px; }
.mpc-upload-input { display: none; }

@media (max-width: 1040px) {
    .mpc-layout,
    .mpc-card-body {
        grid-template-columns: 1fr;
    }
    .mpc-topbar {
        flex-direction: column;
        align-items: stretch;
    }
}
.mpc-btn:disabled,
.mpc-btn[disabled] {
    opacity: 0.45;
    cursor: not-allowed;
    filter: grayscale(0.3);
}
</style>

<div class="mpc-page">
    <?php if ($flash_ok): ?>
        <div class="mpc-flash ok"><?php echo htmlspecialchars($flash_ok); ?></div>
    <?php endif; ?>
    <?php if ($flash_err): ?>
        <div class="mpc-flash err"><?php echo htmlspecialchars($flash_err); ?></div>
    <?php endif; ?>

    <div class="mpc-topbar">
        <div>
            <span class="mpc-kicker">Admin · Colors & Images</span>
            <h1 class="mpc-title"><?php echo htmlspecialchars($product['name']); ?></h1>
            <div class="mpc-meta">
                <span class="mpc-pill">Item Code: <?php echo htmlspecialchars($product['item_code']); ?></span>
                <span class="mpc-pill"><?php echo htmlspecialchars($product['category']); ?> / <?php echo htmlspecialchars($product['sub_category']); ?></span>
                <?php if (!empty($product['brand'])): ?>
                    <span class="mpc-pill"><?php echo htmlspecialchars($product['brand']); ?></span>
                <?php endif; ?>
            </div>
        </div>
        <div class="mpc-toolbar">
            <button type="submit" name="action" value="save_colors" form="bulkSaveForm" class="mpc-btn mpc-btn-primary">💾 Save Changes</button>
            <a href="edit_product.php?id=<?php echo $product_id; ?>" class="mpc-btn mpc-btn-ghost">← Back to Edit Product</a>
        </div>
    </div>

    <div class="mpc-layout">
        <aside>
            <div class="mpc-panel">
                <h3>Add New Color</h3>
                <form method="POST" action="manage_product_colors.php?product_id=<?php echo $product_id; ?>">
                    <?php echo adminCsrfInput(); ?>
                    <input type="hidden" name="action" value="add_color">
                    <div class="mpc-field">
                        <label class="mpc-label" for="new_color_name">Color Name</label>
                        <input class="mpc-input" type="text" id="new_color_name" name="color_name" placeholder="e.g. Matte Black" required>
                    </div>
                    <div class="mpc-field">
                        <label class="mpc-label" for="new_color_code">Color Code</label>
                        <div class="mpc-color-picker-wrap">
                            <input class="mpc-color-input" type="color" id="new_color_code" name="color_code" value="#1a1a1a">
                            <input class="mpc-input" type="text" id="new_color_code_text" value="#1a1a1a" readonly>
                        </div>
                    </div>
                    <div class="mpc-field">
                        <label class="mpc-check"><input type="checkbox" name="is_default"> Set as default color</label>
                    </div>
                    <button type="submit" class="mpc-btn mpc-btn-primary" style="width:100%;">Add Color</button>
                </form>
            </div>

        </aside>

        <section class="mpc-main">
            <form id="bulkSaveForm" method="POST" action="manage_product_colors.php?product_id=<?php echo $product_id; ?>">
                    <?php echo adminCsrfInput(); ?>
                <input type="hidden" name="action" value="save_colors">
            </form>

            <?php if (empty($colors)): ?>
                <div class="mpc-empty">
                    <h3 style="margin-top:0;">No colors added yet</h3>
                    <p style="color:var(--mpc-muted); margin-bottom:0;">Add your first color from the left panel to start managing images.</p>
                </div>
            <?php else: ?>
                <div class="mpc-cards">
                    <?php foreach ($colors as $color): ?>
                        <?php $imgs = $imagesByColor[$color['id']] ?? []; ?>
                        <article class="mpc-card">
                            <div class="mpc-card-head">
                                <div class="mpc-card-title-wrap">
                                    <div class="mpc-swatch" style="background: <?php echo htmlspecialchars($color['color_code']); ?>;"></div>
                                    <div>
                                        <h2 class="mpc-card-title"><?php echo htmlspecialchars($color['color_name']); ?></h2>
                                        <?php $colorStockQty = (int)($stockByColor[(int)$color['id']] ?? 0); ?>
                                        <div class="mpc-card-sub"><?php echo count($imgs); ?> image<?php echo count($imgs) === 1 ? '' : 's'; ?> in this color · <?php echo $colorStockQty; ?> unit<?php echo $colorStockQty === 1 ? '' : 's'; ?> in stock</div>
                                        <?php if (pg_bool($color['is_default'])): ?>
                                            <div class="mpc-default-badge">★ Current default color</div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="mpc-card-actions">
                                    <?php if ($colorStockQty > 0): ?>
                                        <button type="button" class="mpc-btn mpc-btn-danger" disabled title="Stock Out this colour before deleting it.">🗑 Delete Color</button>
                                    <?php else: ?>
                                        <form method="POST" action="manage_product_colors.php?product_id=<?php echo $product_id; ?>" class="admin-confirm-form" data-confirm-title="Delete Colour" data-confirm-message="Are you sure you want to delete this colour and its images? This action cannot be undone." data-confirm-text="Yes, Delete" data-confirm-type="danger">
                    <?php echo adminCsrfInput(); ?>
                                            <input type="hidden" name="action" value="delete_color">
                                            <input type="hidden" name="color_id" value="<?php echo $color['id']; ?>">
                                            <button type="submit" class="mpc-btn mpc-btn-danger">🗑 Delete Color</button>
                                        </form>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="mpc-card-body">
                                <div class="mpc-edit-grid">
                                    <input type="hidden" name="color_ids[]" value="<?php echo $color['id']; ?>" form="bulkSaveForm">

                                    <div class="mpc-field">
                                        <label class="mpc-label" for="color_name_<?php echo $color['id']; ?>">Color Name</label>
                                        <input
                                            class="mpc-input"
                                            type="text"
                                            id="color_name_<?php echo $color['id']; ?>"
                                            name="color_name[<?php echo $color['id']; ?>]"
                                            value="<?php echo htmlspecialchars($color['color_name']); ?>"
                                            form="bulkSaveForm"
                                            required
                                        >
                                    </div>

                                    <div class="mpc-field">
                                        <label class="mpc-label" for="color_code_<?php echo $color['id']; ?>">Color Code</label>
                                        <div class="mpc-color-picker-wrap">
                                            <input
                                                class="mpc-color-input color-picker-sync"
                                                type="color"
                                                id="color_code_<?php echo $color['id']; ?>"
                                                value="<?php echo htmlspecialchars($color['color_code']); ?>"
                                                data-target="color_code_text_<?php echo $color['id']; ?>"
                                                form="bulkSaveForm"
                                            >
                                            <input
                                                class="mpc-input"
                                                type="text"
                                                id="color_code_text_<?php echo $color['id']; ?>"
                                                name="color_code[<?php echo $color['id']; ?>]"
                                                value="<?php echo htmlspecialchars($color['color_code']); ?>"
                                                form="bulkSaveForm"
                                                required
                                            >
                                        </div>
                                    </div>

                                    <div class="mpc-default-row">
                                        <input
                                            type="radio"
                                            id="default_color_<?php echo $color['id']; ?>"
                                            name="default_color_id"
                                            value="<?php echo $color['id']; ?>"
                                            <?php echo pg_bool($color['is_default']) ? 'checked' : ''; ?>
                                            form="bulkSaveForm"
                                        >
                                        <label for="default_color_<?php echo $color['id']; ?>">Use this as the default color</label>
                                    </div>
                                </div>

                                <div class="mpc-images">
                                    <div class="mpc-image-grid">
                                        <?php foreach ($imgs as $img): ?>
                                            <div class="mpc-image-tile">
                                                <div class="mpc-image-preview">
                                                    <img src="../<?php echo htmlspecialchars($img['image_path']); ?>" alt="<?php echo htmlspecialchars($color['color_name']); ?> image">
                                                    <?php if (pg_bool($img['is_main'])): ?>
                                                        <div class="mpc-main-image-badge">★ Main image</div>
                                                    <?php endif; ?>
                                                </div>
                                                <div class="mpc-image-actions">
                                                    <?php if (!pg_bool($img['is_main'])): ?>
                                                        <form method="POST" action="manage_product_colors.php?product_id=<?php echo $product_id; ?>">
                    <?php echo adminCsrfInput(); ?>
                                                            <input type="hidden" name="action" value="set_main">
                                                            <input type="hidden" name="image_id" value="<?php echo $img['id']; ?>">
                                                            <input type="hidden" name="color_id" value="<?php echo $color['id']; ?>">
                                                            <button type="submit" class="mpc-mini-btn">Set Main</button>
                                                        </form>
                                                    <?php else: ?>
                                                        <button type="button" class="mpc-mini-btn" disabled>Main Image</button>
                                                    <?php endif; ?>

                                                    <form method="POST" action="manage_product_colors.php?product_id=<?php echo $product_id; ?>" class="admin-confirm-form" data-confirm-title="Delete Image" data-confirm-message="Are you sure you want to delete this image? This action cannot be undone." data-confirm-text="Yes, Delete" data-confirm-type="danger">
                    <?php echo adminCsrfInput(); ?>
                                                        <input type="hidden" name="action" value="delete_image">
                                                        <input type="hidden" name="image_id" value="<?php echo $img['id']; ?>">
                                                        <input type="hidden" name="color_id" value="<?php echo $color['id']; ?>">
                                                        <button type="submit" class="mpc-mini-btn mpc-mini-btn-danger">Delete</button>
                                                    </form>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>

                                        <div class="mpc-upload-tile">
                                            <strong>+ Add Images</strong>
                                            <p>Upload more files for <?php echo htmlspecialchars($color['color_name']); ?>.</p>
                                            <form method="POST" enctype="multipart/form-data" action="manage_product_colors.php?product_id=<?php echo $product_id; ?>">
                    <?php echo adminCsrfInput(); ?>
                                                <input type="hidden" name="action" value="upload_images">
                                                <input type="hidden" name="color_id" value="<?php echo $color['id']; ?>">
                                                <input class="mpc-upload-input" type="file" id="upload_<?php echo $color['id']; ?>" name="images[]" accept="image/*" multiple onchange="this.form.submit()">
                                                <button type="button" class="mpc-btn mpc-btn-ghost" onclick="document.getElementById('upload_<?php echo $color['id']; ?>').click()">Choose Files</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </section>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const addPicker = document.getElementById('new_color_code');
    const addText = document.getElementById('new_color_code_text');

    if (addPicker && addText) {
        addPicker.addEventListener('input', function () {
            addText.value = this.value;
        });
    }

    document.querySelectorAll('.color-picker-sync').forEach(function (picker) {
        picker.addEventListener('input', function () {
            const targetId = this.dataset.target;
            const target = document.getElementById(targetId);
            if (target) {
                target.value = this.value;
            }
        });
    });

    setTimeout(function () {
        document.querySelectorAll('.mpc-flash').forEach(function (el) {
            el.style.transition = 'opacity .4s ease';
            el.style.opacity = '0';
            setTimeout(function () { el.remove(); }, 450);
        });
    }, 4000);
});
</script>

<?php require_once 'includes/footer.php'; $conn = null; ?>
